#!/bin/sh

TEMPLATE="templates/default.mustache"
EXTENSION=".muttrc"

generate() {
    scheme="$1"
    template="$2"
    extension="$3"
    rm -f "$scheme$extension"
    awk 'NR==FNR {a[$1]=$2;next} {for ( i in a) gsub(i,a[i])}1' FS="," \
        "schemes/$scheme.scheme" "$template" > "$scheme$extension"
}

generate "contrejour-light" "$TEMPLATE" "$EXTENSION"
generate "contrejour-dark" "$TEMPLATE" "$EXTENSION"
